services:
  concert-finder:
    build: .
    ports:
      - "6100:6100"
    env_file:
      - .env.local
    volumes:
      - /mnt/user/appdata/music-spider-service:/app/data
    restart: unless-stopped
