services:
  concert-finder:
    build: .
    ports:
      - "6100:6100"
    env_file:
      - .env.local
    volumes:
      - ./data:/app/data # For an Unraid user, this might look like /mnt/user/appdata/music-spider
    restart: unless-stopped
