// Resident Advisor area IDs and display names, fetched from RA's
// `countries { areas { id name } }` GraphQL query.
export const RA_REGIONS = [
  { id: 403, label: "Aarhus, Denmark" },
  { id: 342, label: "Aberdeen, United Kingdom" },
  { id: 213, label: "Abu Dhabi, United Arab Emirates" },
  { id: 601, label: "Acapulco de Juárez, Mexico" },
  { id: 5, label: "Adelaide, Australia" },
  { id: 466, label: "Afghanistan (All regions)" },
  { id: 632, label: "Aguascalientes, Mexico" },
  { id: 108, label: "Alabama, United States" },
  { id: 109, label: "Alaska, United States" },
  { id: 223, label: "Albania (All regions)" },
  { id: 573, label: "Alberta, Canada" },
  { id: 365, label: "Algarve, Portugal" },
  { id: 307, label: "Algeria (All regions)" },
  { id: 613, label: "Alicante, Spain" },
  { id: 29, label: "Amsterdam, Netherlands" },
  { id: 288, label: "Andorra (All regions)" },
  { id: 567, label: "Andorra la Vella, Andorra" },
  { id: 312, label: "Angola (All regions)" },
  { id: 379, label: "Ankara, Turkey" },
  { id: 417, label: "Antigua and Barbuda (All regions)" },
  { id: 404, label: "Antwerp, Belgium" },
  { id: 45, label: "Argentina (All regions)" },
  { id: 102, label: "Arizona, United States" },
  { id: 110, label: "Arkansas, United States" },
  { id: 264, label: "Armenia (All regions)" },
  { id: 549, label: "Athens, Greece" },
  { id: 532, label: "Atlanta, United States" },
  { id: 540, label: "Auckland, New Zealand" },
  { id: 209, label: "Augsburg, Germany" },
  { id: 321, label: "Austin, United States" },
  { id: 439, label: "Australian Capital Territory, Australia" },
  { id: 159, label: "Austria (All regions)" },
  { id: 270, label: "Azerbaijan (All regions)" },
  { id: 336, label: "Baden-Württemberg, Germany" },
  { id: 296, label: "Bahamas (All regions)" },
  { id: 195, label: "Bahrain (All regions)" },
  { id: 622, label: "Baja California Sur, Mexico" },
  { id: 621, label: "Baja California, Mexico" },
  { id: 543, label: "Bali, Indonesia" },
  { id: 526, label: "Baltimore, United States" },
  { id: 325, label: "Bangalore, India" },
  { id: 453, label: "Bangkok, Thailand" },
  { id: 269, label: "Bangladesh (All regions)" },
  { id: 186, label: "Barbados (All regions)" },
  { id: 20, label: "Barcelona, Spain" },
  { id: 391, label: "Basel, Switzerland" },
  { id: 377, label: "Batumi, Georgia" },
  { id: 357, label: "Bavaria, Germany" },
  { id: 191, label: "Beijing, China" },
  { id: 547, label: "Beirut, Lebanon" },
  { id: 189, label: "Belarus (All regions)" },
  { id: 534, label: "Belfast, United Kingdom" },
  { id: 62, label: "Belgium (All regions)" },
  { id: 562, label: "Belgrade, Serbia" },
  { id: 331, label: "Belize (All regions)" },
  { id: 609, label: "Benidorm, Spain" },
  { id: 418, label: "Benin (All regions)" },
  { id: 409, label: "Bergen, Norway" },
  { id: 34, label: "Berlin, Germany" },
  { id: 330, label: "Bermuda (All regions)" },
  { id: 394, label: "Bern, Switzerland" },
  { id: 419, label: "Bhutan (All regions)" },
  { id: 274, label: "Bielefeld, Germany" },
  { id: 612, label: "Bilbao, Spain" },
  { id: 516, label: "Birmingham, United Kingdom" },
  { id: 298, label: "Bochum, Germany" },
  { id: 373, label: "Bogotá, Colombia" },
  { id: 200, label: "Bolivia (All regions)" },
  { id: 350, label: "Bologna, Italy" },
  { id: 617, label: "Bordeaux, France" },
  { id: 187, label: "Bosnia and Herzegovina (All regions)" },
  { id: 530, label: "Boston, United States" },
  { id: 420, label: "Botswana (All regions)" },
  { id: 208, label: "Brandenburg, Germany" },
  { id: 568, label: "Bratislava, Slovakia" },
  { id: 61, label: "Brazil (All regions)" },
  { id: 225, label: "Bremen, Germany" },
  { id: 535, label: "Brighton, United Kingdom" },
  { id: 12, label: "Brisbane, Australia" },
  { id: 446, label: "Bristol, United Kingdom" },
  { id: 571, label: "British Columbia, Canada" },
  { id: 676, label: "Brno, Czech Republic" },
  { id: 512, label: "Brunei (All regions)" },
  { id: 405, label: "Brussels, Belgium" },
  { id: 381, label: "Bucharest, Romania" },
  { id: 449, label: "Budapest, Hungary" },
  { id: 395, label: "Buenos Aires, Argentina" },
  { id: 443, label: "Buffalo/Rochester, United States" },
  { id: 95, label: "Bulgaria (All regions)" },
  { id: 421, label: "Burkina Faso (All regions)" },
  { id: 513, label: "Burundi (All regions)" },
  { id: 665, label: "Busan, South Korea" },
  { id: 674, label: "Byron Bay, Australia" },
  { id: 137, label: "Calgary, Canada" },
  { id: 375, label: "Cali, Colombia" },
  { id: 308, label: "California, United States" },
  { id: 272, label: "Cambodia (All regions)" },
  { id: 422, label: "Cameroon (All regions)" },
  { id: 649, label: "Campeche, Mexico" },
  { id: 367, label: "Canary Islands, Spain" },
  { id: 4, label: "Canberra, Australia" },
  { id: 100, label: "Cape Town, South Africa" },
  { id: 467, label: "Cape Verde (All regions)" },
  { id: 518, label: "Cardiff, United Kingdom" },
  { id: 207, label: "Cayman Islands (All regions)" },
  { id: 468, label: "Central African Republic (All regions)" },
  { id: 276, label: "Central, France" },
  { id: 52, label: "Central, Italy" },
  { id: 469, label: "Chad (All regions)" },
  { id: 616, label: "Chamonix, France" },
  { id: 311, label: "Changsha, China" },
  { id: 655, label: "Charleston, United States" },
  { id: 652, label: "Charlotte, United States" },
  { id: 588, label: "Charlottetown, Canada" },
  { id: 265, label: "Chemnitz, Germany" },
  { id: 283, label: "Chengdu, China" },
  { id: 327, label: "Chennai, India" },
  { id: 648, label: "Chiapas, Mexico" },
  { id: 17, label: "Chicago, United States" },
  { id: 624, label: "Chihuahua, Mexico" },
  { id: 59, label: "Chile (All regions)" },
  { id: 332, label: "Chongqing, China" },
  { id: 542, label: "Christchurch, New Zealand" },
  { id: 140, label: "Chubu, Japan" },
  { id: 141, label: "Chugoku, Japan" },
  { id: 600, label: "Ciudad Juárez, Mexico" },
  { id: 529, label: "Cleveland, United States" },
  { id: 382, label: "Cluj-Napoca, Romania" },
  { id: 626, label: "Coahuila, Mexico" },
  { id: 636, label: "Colima, Mexico" },
  { id: 143, label: "Cologne, Germany" },
  { id: 163, label: "Colombia (All regions)" },
  { id: 82, label: "Colorado, United States" },
  { id: 564, label: "Columbus, United States" },
  { id: 470, label: "Comoros (All regions)" },
  { id: 111, label: "Connecticut, United States" },
  { id: 402, label: "Copenhagen, Denmark" },
  { id: 387, label: "Cork, Ireland" },
  { id: 26, label: "Costa Rica (All regions)" },
  { id: 658, label: "Crete, Greece" },
  { id: 94, label: "Croatia (All regions)" },
  { id: 238, label: "Cuba (All regions)" },
  { id: 334, label: "Curacao (All regions)" },
  { id: 197, label: "Cyprus (All regions)" },
  { id: 97, label: "Czech Republic (All regions)" },
  { id: 319, label: "Dallas/Fort Worth, United States" },
  { id: 229, label: "Darmstadt, Germany" },
  { id: 441, label: "Darwin, Australia" },
  { id: 112, label: "Delaware, United States" },
  { id: 324, label: "Delhi, India" },
  { id: 424, label: "Democratic Republic of the Congo (All regions)" },
  { id: 99, label: "Denmark (All regions)" },
  { id: 519, label: "Denver, United States" },
  { id: 19, label: "Detroit, United States" },
  { id: 514, label: "Djibouti (All regions)" },
  { id: 472, label: "Dominica (All regions)" },
  { id: 179, label: "Dominican Republic (All regions)" },
  { id: 144, label: "Dortmund / Essen, Germany" },
  { id: 150, label: "Dresden, Germany" },
  { id: 136, label: "Dubai, United Arab Emirates" },
  { id: 386, label: "Dublin, Ireland" },
  { id: 539, label: "Dundee, United Kingdom" },
  { id: 627, label: "Durango, Mexico" },
  { id: 259, label: "Durban, South Africa" },
  { id: 145, label: "Düsseldorf, Germany" },
  { id: 473, label: "East Timor (All regions)" },
  { id: 277, label: "East, France" },
  { id: 160, label: "East, Spain" },
  { id: 185, label: "Ecuador (All regions)" },
  { id: 341, label: "Edinburgh, United Kingdom" },
  { id: 54, label: "Edmonton, Canada" },
  { id: 96, label: "Egypt (All regions)" },
  { id: 177, label: "Eindhoven, Netherlands" },
  { id: 322, label: "El Paso, United States" },
  { id: 135, label: "El Salvador (All regions)" },
  { id: 682, label: "Ensenada, Mexico" },
  { id: 474, label: "Equatorial Guinea (All regions)" },
  { id: 235, label: "Erfurt, Germany" },
  { id: 475, label: "Eritrea (All regions)" },
  { id: 643, label: "Estado de México, Mexico" },
  { id: 184, label: "Estonia (All regions)" },
  { id: 476, label: "Eswatini (All regions)" },
  { id: 458, label: "Ethiopia (All regions)" },
  { id: 610, label: "Faro, Portugal" },
  { id: 494, label: "Federated States of Micronesia (All regions)" },
  { id: 456, label: "Fiji (All regions)" },
  { id: 87, label: "Finland (All regions)" },
  { id: 680, label: "Fire Island, United States" },
  { id: 352, label: "Florence, Italy" },
  { id: 317, label: "Florida, United States" },
  { id: 147, label: "Frankfurt, Germany" },
  { id: 228, label: "Freiburg, Germany" },
  { id: 157, label: "French Riviera, France" },
  { id: 448, label: "French West Indies, France" },
  { id: 477, label: "Gabon (All regions)" },
  { id: 389, label: "Galway, Ireland" },
  { id: 425, label: "Gambia (All regions)" },
  { id: 667, label: "Gdansk, Poland" },
  { id: 392, label: "Geneva, Switzerland" },
  { id: 376, label: "Georgia (All regions)" },
  { id: 64, label: "Georgia, United States" },
  { id: 426, label: "Ghana (All regions)" },
  { id: 545, label: "Ghent, Belgium" },
  { id: 243, label: "Gibraltar (All regions)" },
  { id: 340, label: "Glasgow, United Kingdom" },
  { id: 323, label: "Goa, India" },
  { id: 675, label: "Gold Coast, Australia" },
  { id: 397, label: "Gothenburg, Sweden" },
  { id: 37, label: "Greece (All regions)" },
  { id: 654, label: "Greensboro, United States" },
  { id: 478, label: "Grenada (All regions)" },
  { id: 522, label: "Guadalajara, Mexico" },
  { id: 290, label: "Guam (All regions)" },
  { id: 635, label: "Guanajuato, Mexico" },
  { id: 190, label: "Guangzhou, China" },
  { id: 202, label: "Guatemala (All regions)" },
  { id: 645, label: "Guerrero, Mexico" },
  { id: 479, label: "Guinea (All regions)" },
  { id: 480, label: "Guinea-Bissau (All regions)" },
  { id: 481, label: "Guyana (All regions)" },
  { id: 482, label: "Haiti (All regions)" },
  { id: 586, label: "Halifax, Canada" },
  { id: 148, label: "Hamburg, Germany" },
  { id: 662, label: "Hamilton, Canada" },
  { id: 234, label: "Hangzhou, China" },
  { id: 146, label: "Hannover, Germany" },
  { id: 556, label: "Hanoi, Vietnam" },
  { id: 133, label: "Hawaii, United States" },
  { id: 219, label: "Heidelberg, Germany" },
  { id: 407, label: "Helsinki, Finland" },
  { id: 354, label: "Hesse, Germany" },
  { id: 639, label: "Hidalgo, Mexico" },
  { id: 554, label: "Ho Chi Minh City, Vietnam" },
  { id: 6, label: "Hobart, Australia" },
  { id: 138, label: "Hokkaido, Japan" },
  { id: 167, label: "Honduras (All regions)" },
  { id: 71, label: "Hong Kong, China" },
  { id: 63, label: "Houston, United States" },
  { id: 78, label: "Hungary (All regions)" },
  { id: 326, label: "Hyderabad, India" },
  { id: 383, label: "Iasi, Romania" },
  { id: 25, label: "Ibiza, Spain" },
  { id: 201, label: "Iceland (All regions)" },
  { id: 113, label: "Idaho, United States" },
  { id: 359, label: "Illinois, United States" },
  { id: 85, label: "Indiana, United States" },
  { id: 76, label: "Indonesia (All regions)" },
  { id: 678, label: "Inland Empire, United States" },
  { id: 114, label: "Iowa, United States" },
  { id: 206, label: "Iran (All regions)" },
  { id: 598, label: "Irapuato, Mexico" },
  { id: 483, label: "Iraq (All regions)" },
  { id: 43, label: "Ireland (All regions)" },
  { id: 42, label: "Israel (All regions)" },
  { id: 73, label: "Istanbul, Turkey" },
  { id: 423, label: "Ivory Coast (All regions)" },
  { id: 380, label: "Izmir, Turkey" },
  { id: 314, label: "Jacksonville, United States" },
  { id: 569, label: "Jakarta, Indonesia" },
  { id: 634, label: "Jalisco, Mexico" },
  { id: 221, label: "Jamaica (All regions)" },
  { id: 210, label: "Jena, Germany" },
  { id: 445, label: "Jinan, China" },
  { id: 258, label: "Johannesburg, South Africa" },
  { id: 192, label: "Jordan (All regions)" },
  { id: 66, label: "Kansai, Japan" },
  { id: 90, label: "Kansas, United States" },
  { id: 252, label: "Kanto, Japan" },
  { id: 220, label: "Karlsruhe, Germany" },
  { id: 233, label: "Kassel, Germany" },
  { id: 297, label: "Kazakhstan (All regions)" },
  { id: 115, label: "Kentucky, United States" },
  { id: 214, label: "Kenya (All regions)" },
  { id: 484, label: "Kiribati (All regions)" },
  { id: 372, label: "Kolkata, India" },
  { id: 362, label: "Kosovo (All regions)" },
  { id: 455, label: "Krakow, Poland" },
  { id: 237, label: "Krasnodar, Russia" },
  { id: 36, label: "Kuala Lumpur, Malaysia" },
  { id: 371, label: "Kunming, China" },
  { id: 236, label: "Kuwait (All regions)" },
  { id: 517, label: "Kyiv, Ukraine" },
  { id: 663, label: "Kyoto, Japan" },
  { id: 485, label: "Kyrgyzstan (All regions)" },
  { id: 139, label: "Kyushu, Japan" },
  { id: 557, label: "Lagos, Nigeria" },
  { id: 611, label: "Lagos, Portugal" },
  { id: 427, label: "Laos (All regions)" },
  { id: 527, label: "Las Vegas, United States" },
  { id: 93, label: "Latvia (All regions)" },
  { id: 393, label: "Lausanne, Switzerland" },
  { id: 101, label: "Lebanon (All regions)" },
  { id: 346, label: "Leeds, United Kingdom" },
  { id: 149, label: "Leipzig, Germany" },
  { id: 487, label: "Lesotho (All regions)" },
  { id: 488, label: "Liberia (All regions)" },
  { id: 489, label: "Libya (All regions)" },
  { id: 490, label: "Liechtenstein (All regions)" },
  { id: 619, label: "Lille, France" },
  { id: 388, label: "Limerick, Ireland" },
  { id: 53, label: "Lisbon, Portugal" },
  { id: 91, label: "Lithuania (All regions)" },
  { id: 343, label: "Liverpool, United Kingdom" },
  { id: 563, label: "Ljubljana, Slovenia" },
  { id: 677, label: "Lodz, Poland" },
  { id: 13, label: "London, United Kingdom" },
  { id: 23, label: "Los Angeles, United States" },
  { id: 65, label: "Louisiana, United States" },
  { id: 358, label: "Lower Saxony, Germany" },
  { id: 199, label: "Luxembourg (All regions)" },
  { id: 337, label: "Lyon, France" },
  { id: 244, label: "Macau, China" },
  { id: 428, label: "Madagascar (All regions)" },
  { id: 594, label: "Madison, United States" },
  { id: 41, label: "Madrid, Spain" },
  { id: 116, label: "Maine, United States" },
  { id: 687, label: "Mainz, Germany" },
  { id: 608, label: "Malaga, Spain" },
  { id: 204, label: "Malawi (All regions)" },
  { id: 429, label: "Maldives (All regions)" },
  { id: 491, label: "Mali (All regions)" },
  { id: 661, label: "Mallorca, Spain" },
  { id: 398, label: "Malmo, Sweden" },
  { id: 164, label: "Malta (All regions)" },
  { id: 344, label: "Manchester, United Kingdom" },
  { id: 565, label: "Manila, Philippines" },
  { id: 579, label: "Manitoba, Canada" },
  { id: 153, label: "Mannheim, Germany" },
  { id: 338, label: "Marseille, France" },
  { id: 492, label: "Marshall Islands (All regions)" },
  { id: 117, label: "Maryland, United States" },
  { id: 79, label: "Massachusetts, United States" },
  { id: 493, label: "Mauritania (All regions)" },
  { id: 304, label: "Mauritius (All regions)" },
  { id: 226, label: "Mecklenburg-Vorpommern, Germany" },
  { id: 374, label: "Medellin, Colombia" },
  { id: 2, label: "Melbourne, Australia" },
  { id: 683, label: "Memphis, United States" },
  { id: 603, label: "Mérida, Mexico" },
  { id: 399, label: "Mexico City, Mexico" },
  { id: 38, label: "Miami, United States" },
  { id: 360, label: "Michigan, United States" },
  { id: 638, label: "Michoacán, Mexico" },
  { id: 14, label: "Midlands, United Kingdom" },
  { id: 347, label: "Milan, Italy" },
  { id: 593, label: "Milwaukee, United States" },
  { id: 590, label: "Minneapolis/St Paul, United States" },
  { id: 81, label: "Minnesota, United States" },
  { id: 103, label: "Mississippi, United States" },
  { id: 118, label: "Missouri, United States" },
  { id: 198, label: "Moldova (All regions)" },
  { id: 158, label: "Monaco (All regions)" },
  { id: 584, label: "Moncton, Canada" },
  { id: 212, label: "Mongolia (All regions)" },
  { id: 119, label: "Montana, United States" },
  { id: 193, label: "Montenegro (All regions)" },
  { id: 70, label: "Monterrey, Mexico" },
  { id: 384, label: "Montevideo, Uruguay" },
  { id: 339, label: "Montpellier, France" },
  { id: 40, label: "Montreal, Canada" },
  { id: 604, label: "Morelia, Mexico" },
  { id: 641, label: "Morelos, Mexico" },
  { id: 173, label: "Morocco (All regions)" },
  { id: 88, label: "Moscow, Russia" },
  { id: 305, label: "Mozambique (All regions)" },
  { id: 328, label: "Mumbai, India" },
  { id: 151, label: "Munich, Germany" },
  { id: 275, label: "Münster, Germany" },
  { id: 335, label: "Myanmar (All regions)" },
  { id: 659, label: "Mykonos, Greece" },
  { id: 660, label: "Nairobi, Kenya" },
  { id: 495, label: "Namibia (All regions)" },
  { id: 281, label: "Nanjing, China" },
  { id: 536, label: "Nantes, France" },
  { id: 406, label: "Naples, Italy" },
  { id: 653, label: "Nashville, United States" },
  { id: 496, label: "Nauru (All regions)" },
  { id: 629, label: "Nayarit, Mexico" },
  { id: 120, label: "Nebraska, United States" },
  { id: 287, label: "Nepal (All regions)" },
  { id: 176, label: "Netherlands (All regions)" },
  { id: 47, label: "Nevada, United States" },
  { id: 583, label: "New Brunswick, Canada" },
  { id: 121, label: "New Hampshire, United States" },
  { id: 48, label: "New Jersey, United States" },
  { id: 122, label: "New Mexico, United States" },
  { id: 606, label: "New Orleans, United States" },
  { id: 433, label: "New South Wales, Australia" },
  { id: 8, label: "New York City, United States" },
  { id: 605, label: "New York State, United States" },
  { id: 345, label: "Newcastle, United Kingdom" },
  { id: 581, label: "Newfoundland and Labrador, Canada" },
  { id: 249, label: "Nicaragua (All regions)" },
  { id: 614, label: "Nice, France" },
  { id: 497, label: "Niger (All regions)" },
  { id: 303, label: "Nigeria (All regions)" },
  { id: 672, label: "Nijmegen, Netherlands" },
  { id: 123, label: "North Carolina, United States" },
  { id: 124, label: "North Dakota, United States" },
  { id: 589, label: "North Island, New Zealand" },
  { id: 498, label: "North Macedonia (All regions)" },
  { id: 353, label: "North Rhine-Westphalia, Germany" },
  { id: 278, label: "North, France" },
  { id: 171, label: "North, Italy" },
  { id: 170, label: "North, Spain" },
  { id: 16, label: "North, United Kingdom" },
  { id: 35, label: "Northern Ireland, United Kingdom" },
  { id: 440, label: "Northern Territory, Australia" },
  { id: 575, label: "Northwest Territories, Canada" },
  { id: 57, label: "Norway (All regions)" },
  { id: 544, label: "Nottingham, United Kingdom" },
  { id: 585, label: "Nova Scotia, Canada" },
  { id: 628, label: "Nuevo León, Mexico" },
  { id: 576, label: "Nunavut, Canada" },
  { id: 154, label: "Nürnberg, Germany" },
  { id: 599, label: "Oaxaca de Juárez, Mexico" },
  { id: 646, label: "Oaxaca, Mexico" },
  { id: 515, label: "Odense, Denmark" },
  { id: 84, label: "Ohio, United States" },
  { id: 242, label: "Okinawa, Japan" },
  { id: 104, label: "Oklahoma, United States" },
  { id: 215, label: "Oman (All regions)" },
  { id: 570, label: "Ontario, Canada" },
  { id: 679, label: "Orange County, United States" },
  { id: 410, label: "Oregon, United States" },
  { id: 315, label: "Orlando, United States" },
  { id: 664, label: "Osaka, Japan" },
  { id: 408, label: "Oslo, Norway" },
  { id: 162, label: "Other regions, India" },
  { id: 74, label: "Ottawa, Canada" },
  { id: 166, label: "Pakistan (All regions)" },
  { id: 499, label: "Palau (All regions)" },
  { id: 368, label: "Palestine (All regions)" },
  { id: 596, label: "Palm Springs, United States" },
  { id: 92, label: "Panama (All regions)" },
  { id: 500, label: "Papua New Guinea (All regions)" },
  { id: 180, label: "Paraguay (All regions)" },
  { id: 44, label: "Paris, France" },
  { id: 80, label: "Pennsylvania, United States" },
  { id: 538, label: "Pereira, Colombia" },
  { id: 3, label: "Perth, Australia" },
  { id: 86, label: "Peru (All regions)" },
  { id: 528, label: "Philadelphia, United States" },
  { id: 168, label: "Philippines (All regions)" },
  { id: 591, label: "Phoenix, United States" },
  { id: 531, label: "Pittsburgh, United States" },
  { id: 684, label: "Playa del Carmen, Mexico" },
  { id: 671, label: "Podgorica, Montenegro" },
  { id: 69, label: "Poland (All regions)" },
  { id: 125, label: "Portland, United States" },
  { id: 364, label: "Porto, Portugal" },
  { id: 686, label: "Portsmouth, United Kingdom" },
  { id: 366, label: "Portugal (All regions)" },
  { id: 666, label: "Poznan, Poland" },
  { id: 451, label: "Prague, Czech Republic" },
  { id: 548, label: "Pretoria, South Africa" },
  { id: 587, label: "Prince Edward Island, Canada" },
  { id: 572, label: "Province of Quebec, Canada" },
  { id: 681, label: "Provincetown, United States" },
  { id: 551, label: "Puebla (city), Mexico" },
  { id: 642, label: "Puebla, Mexico" },
  { id: 525, label: "Puerto Escondido, Mexico" },
  { id: 181, label: "Puerto Rico (All regions)" },
  { id: 550, label: "Puerto Vallarta, Mexico" },
  { id: 329, label: "Pune, India" },
  { id: 203, label: "Qatar (All regions)" },
  { id: 447, label: "Qingdao, China" },
  { id: 285, label: "Quanzhou, China" },
  { id: 250, label: "Quebec City, Canada" },
  { id: 435, label: "Queensland, Australia" },
  { id: 637, label: "Querétaro, Mexico" },
  { id: 651, label: "Quintana Roo, Mexico" },
  { id: 224, label: "Regensburg, Germany" },
  { id: 578, label: "Regina, Canada" },
  { id: 620, label: "Rennes, France" },
  { id: 471, label: "Republic of the Congo (All regions)" },
  { id: 232, label: "Rest of Russia, Russia" },
  { id: 266, label: "Rhineland-Palatinate, Germany" },
  { id: 127, label: "Rhode Island, United States" },
  { id: 553, label: "Richmond, United States" },
  { id: 560, label: "Riga, Latvia" },
  { id: 401, label: "Rio de Janeiro, Brazil" },
  { id: 50, label: "Romania (All regions)" },
  { id: 351, label: "Rome, Italy" },
  { id: 174, label: "Rotterdam, Netherlands" },
  { id: 369, label: "Rwanda (All regions)" },
  { id: 333, label: "Saarland, Germany" },
  { id: 310, label: "Sacramento, United States" },
  { id: 432, label: "Saint Kitts and Nevis (All regions)" },
  { id: 431, label: "Saint Lucia (All regions)" },
  { id: 363, label: "Saint Martin (All regions)" },
  { id: 231, label: "Saint Petersburg, Russia" },
  { id: 592, label: "Salt Lake City, United States" },
  { id: 416, label: "Samoa (All regions)" },
  { id: 320, label: "San Antonio, United States" },
  { id: 309, label: "San Diego, United States" },
  { id: 218, label: "San Francisco/Oakland, United States" },
  { id: 602, label: "San José del Cabo, Mexico" },
  { id: 552, label: "San Jose, United States" },
  { id: 631, label: "San luis Potosi, Mexico" },
  { id: 501, label: "San Marino (All regions)" },
  { id: 597, label: "Santiago de Querétaro, Mexico" },
  { id: 385, label: "Santiago, Chile" },
  { id: 400, label: "Sao Paulo, Brazil" },
  { id: 502, label: "Sao Tome and Principe (All regions)" },
  { id: 673, label: "Sardinia, Italy" },
  { id: 577, label: "Saskatchewan, Canada" },
  { id: 299, label: "Saudi Arabia (All regions)" },
  { id: 227, label: "Saxony-Anhalt, Germany" },
  { id: 356, label: "Saxony, Germany" },
  { id: 273, label: "Schleswig-Holstein, Germany" },
  { id: 30, label: "Scotland, United Kingdom" },
  { id: 46, label: "Seattle, United States" },
  { id: 370, label: "Senegal (All regions)" },
  { id: 537, label: "Seoul, South Korea" },
  { id: 77, label: "Serbia (All regions)" },
  { id: 222, label: "Seychelles (All regions)" },
  { id: 68, label: "Shanghai, China" },
  { id: 520, label: "Sheffield, United Kingdom" },
  { id: 282, label: "Shenyang, China" },
  { id: 361, label: "Shenzhen, China" },
  { id: 294, label: "Shikoku, Japan" },
  { id: 302, label: "Sicily, Italy" },
  { id: 503, label: "Sierra Leone (All regions)" },
  { id: 625, label: "Sinaloa, Mexico" },
  { id: 51, label: "Singapore (All regions)" },
  { id: 670, label: "Skopje, North Macedonia" },
  { id: 98, label: "Slovakia (All regions)" },
  { id: 142, label: "Slovenia (All regions)" },
  { id: 558, label: "Sofia, Bulgaria" },
  { id: 504, label: "Solomon Islands (All regions)" },
  { id: 457, label: "Somalia (All regions)" },
  { id: 623, label: "Sonora, Mexico" },
  { id: 15, label: "South + East, United Kingdom" },
  { id: 260, label: "South Africa (All regions)" },
  { id: 436, label: "South Australia, Australia" },
  { id: 105, label: "South Carolina, United States" },
  { id: 128, label: "South Dakota, United States" },
  { id: 156, label: "South East, France" },
  { id: 49, label: "South Island, New Zealand" },
  { id: 75, label: "South Korea (All regions)" },
  { id: 415, label: "South Sudan (All regions)" },
  { id: 286, label: "South West, France" },
  { id: 172, label: "South, Italy" },
  { id: 169, label: "South, Spain" },
  { id: 685, label: "Southampton, United Kingdom" },
  { id: 289, label: "Sri Lanka (All regions)" },
  { id: 582, label: "St. Johns, Canada" },
  { id: 396, label: "Stockholm, Sweden" },
  { id: 615, label: "Strasbourg, France" },
  { id: 463, label: "Streamland (All regions)" },
  { id: 152, label: "Stuttgart, Germany" },
  { id: 414, label: "Sudan (All regions)" },
  { id: 505, label: "Suriname (All regions)" },
  { id: 217, label: "Suzhou, China" },
  { id: 58, label: "Sweden (All regions)" },
  { id: 60, label: "Switzerland (All regions)" },
  { id: 1, label: "Sydney, Australia" },
  { id: 506, label: "Syria (All regions)" },
  { id: 647, label: "Tabasco, Mexico" },
  { id: 412, label: "Taipei, Taiwan" },
  { id: 55, label: "Taiwan (All regions)" },
  { id: 452, label: "Tajikistan (All regions)" },
  { id: 566, label: "Tallinn, Estonia" },
  { id: 633, label: "Tamaulipas, Mexico" },
  { id: 316, label: "Tampa Bay, United States" },
  { id: 271, label: "Tanzania (All regions)" },
  { id: 438, label: "Tasmania, Australia" },
  { id: 188, label: "Tbilisi, Georgia" },
  { id: 413, label: "Tel Aviv, Israel" },
  { id: 72, label: "Tennessee, United States" },
  { id: 318, label: "Texas, United States" },
  { id: 67, label: "Thailand (All regions)" },
  { id: 178, label: "The Hague, Netherlands" },
  { id: 657, label: "Thessaloniki, Greece" },
  { id: 355, label: "Thuringia, Germany" },
  { id: 279, label: "Tianjin, China" },
  { id: 524, label: "Tijuana, Mexico" },
  { id: 546, label: "Timisoara, Romania" },
  { id: 669, label: "Tirana, Albania" },
  { id: 640, label: "Tlaxcala, Mexico" },
  { id: 507, label: "Togo (All regions)" },
  { id: 254, label: "Tohoku, Japan" },
  { id: 27, label: "Tokyo, Japan" },
  { id: 508, label: "Tonga (All regions)" },
  { id: 28, label: "Toronto, Canada" },
  { id: 618, label: "Toulouse, France" },
  { id: 442, label: "Trinidad and Tobago (All regions)" },
  { id: 595, label: "Tucson, United States" },
  { id: 523, label: "Tulum, Mexico" },
  { id: 196, label: "Tunisia (All regions)" },
  { id: 348, label: "Turin, Italy" },
  { id: 378, label: "Turkey (All regions)" },
  { id: 509, label: "Turkmenistan (All regions)" },
  { id: 510, label: "Tuvalu (All regions)" },
  { id: 306, label: "Uganda (All regions)" },
  { id: 165, label: "Ukraine (All regions)" },
  { id: 194, label: "Uruguay (All regions)" },
  { id: 106, label: "Utah, United States" },
  { id: 175, label: "Utrecht, Netherlands" },
  { id: 216, label: "Uzbekistan (All regions)" },
  { id: 607, label: "Valencia, Spain" },
  { id: 39, label: "Vancouver, Canada" },
  { id: 511, label: "Vanuatu (All regions)" },
  { id: 182, label: "Venezuela (All regions)" },
  { id: 349, label: "Venice, Italy" },
  { id: 644, label: "Veracruz, Mexico" },
  { id: 129, label: "Vermont, United States" },
  { id: 434, label: "Victoria, Australia" },
  { id: 450, label: "Vienna, Austria" },
  { id: 205, label: "Vietnam (All regions)" },
  { id: 561, label: "Vilnius, Lithuania" },
  { id: 130, label: "Virginia, United States" },
  { id: 454, label: "Warsaw, Poland" },
  { id: 22, label: "Washington DC, United States" },
  { id: 411, label: "Washington State, United States" },
  { id: 689, label: "Waterford, Ireland" },
  { id: 541, label: "Wellington, New Zealand" },
  { id: 24, label: "West + Wales, United Kingdom" },
  { id: 131, label: "West Virginia, United States" },
  { id: 155, label: "West, France" },
  { id: 437, label: "Western Australia, Australia" },
  { id: 688, label: "Wiesbaden, Germany" },
  { id: 656, label: "Wilmington, United States" },
  { id: 161, label: "Windsor, Canada" },
  { id: 580, label: "Winnipeg, Canada" },
  { id: 107, label: "Wisconsin, United States" },
  { id: 668, label: "Wroclaw, Poland" },
  { id: 280, label: "Wuhan, China" },
  { id: 132, label: "Wyoming, United States" },
  { id: 444, label: "Xi'an, China" },
  { id: 284, label: "Xiamen, China" },
  { id: 650, label: "Yucátan, Mexico" },
  { id: 574, label: "Yukon, Canada" },
  { id: 630, label: "Zacatecas, Mexico" },
  { id: 559, label: "Zagreb, Croatia" },
  { id: 465, label: "Zambia (All regions)" },
  { id: 313, label: "Zimbabwe (All regions)" },
  { id: 390, label: "Zurich, Switzerland" },
];
